<!DOCTYPE html>
<html>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script src="../js/alertas.js"></script>
<div class="row">

   <h1 class="userT">Usuarios</h1>
  <div class="row">
   <?php if(count($user)>0):?>

   <?php header("Content-type: text/html; charset=utf8"); ?>
  </div>


  <table class="table table-hover">
  <thead>
 
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre(s)</th>
      <th scope="col">Apellido Paterno</th>
      <th scope="col">Apellido Materno</th>
      <th scope="col">Acción</th>
    </tr>
  </thead>
    <tbody>

    
      <?php foreach ($user as $user) : ?>
      

    <tr>
        <td><?php echo $user['id']; ?></td>
        <td><?php echo $user['nombre']; ?></td>
        <td><?php echo $user['apPat']; ?></td>
        <td><?php echo $user['apMat']; ?></td>
        </td>

        <td><a href="<?php echo $this->url('crud', ['action' => 'edit', 'id' =>$user['id']]);?>"class="btn btn-info">Modificar</a>
        </td>
        

        <td>  <a onclick="borrar(<?php echo $user['id']; ?>)" href="#" 
        class="btn btn-danger"> Eliminar </a></td>   

    </tr>
  
     <?php endforeach; ?>
      <?php else:?>
      <tr>
      <center><td>La tabla no contiene datos </td></center>
      </tr>
      <?php endif;?>

      <tr>
          <a href="<?php echo $this->basePath('crud/add'); ?>" class="btn btn-primary btn-default">Agregar</a>      
      </tr>
      
     
    </tbody>
  
    </table>


</html>